export {
  getPatient,
  getConditions,
  getObservations,
  getMedicationRequests,
  getProcedures,
  getAge,
  getGender,
  hasActiveCondition,
  getLatestObservation,
  getObservationValue,
  hasActiveMedication,
  hasMedicationContaining,
  daysSinceProcedure,
} from "./queries";
